sublimelsp/LSP-json

LSP-json.sublime-settings, package-lock.json, package.json, plugin.py
Continued from #3.
`"vscode-json-languageserver": "=1.2.1"` works for me while `"vscode-json-languageserver": "=1.2.2"` doesn't.
The latest version is `1.2.2`.
https://www.npmjs.com/package/vscode-json-languageserver/v/1.2.1?activeTab=versions
=> Replace vscode-json-languageserver-bin with vscode-json-languageserver

schemas/jsconfig.json, schemas/package-json-eslint.json, schemas/sublime-build.json, schemas/sublime-color-scheme.json, schemas/sublime-commands.json, schemas/sublime-completions.json, schemas/sublime-keymap.json, schemas/sublime-macro.json, schemas/sublime-menu.json, schemas/sublime-mousemap.json, schemas/sublime-project.json, schemas/sublime-settings.json, schemas/sublime-theme.json, schemas/tsconfig.json, schemas/vscode-base.json
If there was more than one object in context array, and those didn't
follow the same schema then warning was triggered.
=> Fix multiple items in context triggering a warning

schemas/preferences.sublime-settings.json, schemas/sublime-keymap.json
- Majorly I would like to push `fix(schema): add some legal values in ST 3`.
- Settings in `fix(schema): add some undocumented settings` does work (in 3211) but not officially documented. See https://thume.ca/2016/12/03/disassembling-sublime-text/
=> Improve JSON schema

schemas/preferences.sublime-settings.json
This false warning whenever I open my preferences file has bothered me for a while...
=> Fix a schema value for font_size in Preferences.sublime-settings

lsp-json-schemas_extra.json, plugin.py
Also fixed an issue where schema list was re-sent to all running
instances of server on new one being created. Only notify the new instance.
Resolves #51
=> Encode schema file_patterns internally to simplify authoring

schemas/sublime-color-scheme.json
Modified `sublime-color-scheme` to add color previews
=> show color previews in sublime color schemes

schemas/sublime-color-scheme.json
* Typo in "selection_foreground"
* Duplicate colors in hashed syntax highlighting are allowed
=> Fixes for color scheme schema

schemas/preferences.sublime-settings.json, schemas/syntax.sublime-settings.json
The global preferences were missing tooltip and validation for all
EditorSettings. This was due to schema for "auto_complete_triggers"
not matching (due to missing the "rhs_empty" property in schema) and
thus the whole "anyOf" schema becoming invalid. Since that item of anyOf
became invalid, the other was tested and matched (because
"additionalProperties" are allowed).
Use "allOf" instead which works correctly for this case.
@AmjadHD
=> Fix schema missing for half of the global preferences

lsp-json-schemas_extra.json, schemas/preferences.sublime-settings.json, schemas/sublime-base.json, schemas/sublime-build.json, schemas/sublime-color-scheme.json, schemas/sublime-commands.json, schemas/sublime-completions.json, schemas/sublime-keymap.json, schemas/sublime-macro.json, schemas/sublime-menu.json, schemas/sublime-mousemap.json, schemas/sublime-package-schema.json, schemas/sublime-project.json, schemas/sublime-settings.json, schemas/sublime-theme.json, schemas/syntax.sublime-settings.json
Created a "sublime-base" schema that combines draft-07 and extensions introduced
by VSCode. This makes completions work to suggest things like
"markdownDescription" and a couple of other from
https://github.com/microsoft/vscode-json-languageservice/blob/master/src/jsonSchema.ts
I have not included all as some were not very relevant.
=> Suggest VSCode schema extension properties in sublime-package.json

plugin.py
This makes my RPC logs somewhat more insightful, e.g.
```
::  -> LSP-json json/schemaAssociations: <params with 56392 characters>
:: <-- LSP-json vscode/content(0): sublime://schemas/sublime-base
:: >>> LSP-json 0: {"$id": "sublime://schemas/sublime-base", "$ref": "#/definitions/VSCodeSchemaExtensionRoot", "$schema": "http://json-schema.org/draft-07/schema#", "definitions": {"VSCodeSchemaExtensionProperties": {"properties": {"additionalItems": {"$ref": "#/definitions/VSCodeSchemaExtensionRoot"}, "additionalProperties": {"$ref": "#/definitions/VSCodeSchemaExtensionRoot"}, "allOf": {"$ref": "#/definitions/schemaArray"}, "anyOf": {"$ref": "#/definitions/schemaArray"}, "defaultSnippets": {"description": "Additional snippets to extend completions with.", "items": {"additionalProperties": …
```
=> Do not prettify json strings in requests/responses

schemas/preferences.sublime-settings.json
`index_skip_unknown_extensions` is the valid alternative in recent ST builds.
=> Remove invalid index_exclude_unknown_extensions

schemas/sublime-build.json
All `sublime-...` files may be assigned as file name only value as the basic idea is to have unique file names already. Path part is therefore optional to enforce usage of certain files.
The path is crucial for TextMate values (e.g. `tmLanguage` or `hidden-tmLanguage`) though.
=> Fix build system "syntax" key pattern

plugin.py
The completions are typically triggered due to "auto_complete_selector"
so handling that command shouldn't be necessary.
=> Don't show error on server triggering "editor.action.triggerSuggest"

LSP-json.sublime-settings, plugin.py
With the latest version of lsp_utils a change was introduced [1] that allows using a locally
managed node runtime instead of the system one. For that to work, the "node" command
needs to use a variable.
[1] https://github.com/sublimelsp/lsp_utils/commit/403345a0c5c15e84802c712044c630a9fb236b9d
=> Fix: Use ${node_bin} for the node binary

lsp-json-schemas.json, scripts/update_schemas.py
Those schemas were skipped, but we need those if we want to use the new 2019-09(ex. draft-8) schema:
Before this PR:
Previously we could not assign the 2019-09 draft to a schema with the "$schema" keyword.
After:
Now we can assign the 2019-09 draft to a schema with the "$schema" keyword.
=> Include schemas that don't have a fileMatch

schemas/preferences.sublime-settings.json
This PR adds some undocumented settings to the preferences schema. See the corresponding commits for details.
References:
1. https://github.com/SublimeText/PackageDev/pull/344
2. https://github.com/SublimeText/PackageDev/pull/343
3. https://github.com/sublimehq/sublime_text/issues/4024#issuecomment-831017864
=> Add a few undocumented settings to the preferences schema

schemas/sublime-keymap.json
This PR adds newly added context keys of the 4K build series to the keymap schema. 
Note: These aren't in the official documentation yet. There is an open issue for it https://github.com/sublimehq/sublime_text/issues/4063
Notes:
1. I haven't added `is_javadoc` because I don't know what it does as a context key. I have marked the description for it as a TODO in `PackageDev`. 
2. `panel_type` is a new one (not yet added to `PackageDev`), added in 4097. (Will do so in a future PR to it)
=> Add new context keys of 4K builds to the keymap schema.

schemas/preferences.sublime-settings.json
Reported on discord - https://discord.com/channels/280102180189634562/280157083356233728/849390510367834125
Rename `squared` to `square`, as `square` is the valid enum value.
=> Fix file_tab_style setting

schemas/preferences.sublime-settings.json
This PR adds the `reveal_menu` setting to the settings schema. Introduced in 4108.
=> Add the "reveal_menu" setting

LSP-json.sublime-settings
This allows vscode-json-language-server to work on in-memory buffers. So you can open a new scratch tab, set the syntax to "JSON", and the session will attach. Depends on https://github.com/sublimelsp/LSP/pull/1758
=> Set up URI schemes

schemas/preferences.sublime-settings.json
This PR adds the `syntax_detection_size_limit` setting to the settings schema. Introduced in 4110.
=> Add the `syntax_detection_size_limit` setting.

schemas/preferences.sublime-settings.json
This PR adds the 3 new settings introduced in ST 4114 that allows a user to configure the number of matches/file sizes when using certain `Find` options. More details can be seen in the commits.
=> Add new settings introduced in ST 4114 to the preferences schema

schemas/preferences.sublime-settings.json
This PR adds `use_find_clipboard` setting to preferences schema. Introduced in 4115.
=> Add setting `use_find_clipboard`.

schemas/preferences.sublime-settings.json
This PR updates the `sublime_merge_path` setting, since as of 4116, it can be set to `null` to hide SM integrations in the form of context/side bar menu items.
=> Update the `sublime_merge_path` setting.

schemas/preferences.sublime-settings.json
This PR adds newly added 4127 settings `open_tabs_after_current` & `update_system_recent_files` to the preferences schema.
=> Add new 4127 settings to preferences schema.

schemas/preferences.sublime-settings.json
This PR adds support for newly added settings `sub_word_separators` & `goto_anything_exclude_gitignore` added in Build 4130.
=> [Preferences] Add new settings introduced in Build 4130.

schemas/preferences.sublime-settings.json
I wanted to do this with the last PR but I forgot. This PR updates the `dictionary` setting. Earlier it was just a string which was a package resource path pointing to the dictionary, but from Build 4123 onward, it can be a list of dictionaries as well.
```json
// Word list to use for spell checking. May also be a list of dictionaries.
"dictionary": "Packages/Language - English/en_US.dic",
```
=> [Preferences] Update the `dictionary` setting.

lsp-json-schemas.json, plugin.py, scripts/update_schemas.py
This PR updates the schemas. 9341c8bc1aa03349557968158f5083eb5d419604
This PR should fix #109 13ca3c4a3cb66f270b3dfa7b8bd104780c16d0a6 but ... this still doesn't fix the issue.
The `/messages.json` schema is still applied in Packages folder, even though I added the following string `"!/Packages/**/messages.json"` to explicitly not match that case.
I am not sure how to tell the server to not apply the /messages.json schema if inside /Packages/ directory.
Any pointers are welcome.
=> Ignore messages.json schema to aviod conflicts with ST packages

plugin.py, schema_store.py
Felt that `plugin.py` is getting too big so separated some code into another file. Should have no functional changes.
=> refactor: separate SchemaStore into its own file

plugin.py, schema_store.py
Make loading of schemas happen in a single message loop iteration rather than unnecessarily hopping a couple of times onto the async thread while we were already on the async thread.
Fixes https://github.com/sublimelsp/LSP/issues/2238 by blocking the async thread and not letting us request diagnostics until schemas have loaded.
=> make schema loading block the async thread

plugin.py
Only node 18+ supports imports using the `node:` prefix.
Fixes #171
=> bump minimum node version to 18, following server update

commands.py
Adapt to changes (https://github.com/sublimelsp/LSP/pull/2393) in (yet to be released at the time of writing this) LSP 1.28.0.
> [!WARNING]
> The changes need to be released at the same time as the new version of LSP
=> Adapt to API change in LSP

README.md, plugin.py, sublime-package.json
Resolve relative paths in `userSchemas` and convert to URIs. Relative paths are resolved relative to the first workspace folder.
Resolves #148
=> Support relative file paths in `userSchemas`

schemas/preferences.sublime-settings.json
closes https://github.com/sublimelsp/LSP-json/issues/180
=> Fix rulers

LSP-json.sublime-settings
Note that currently the language server gives warnings about trailing comma.
Let's follow https://github.com/microsoft/vscode/pull/236012 to see if there be some ways to suppress them.
=> Add `bun.lock` to default `jsonc.patterns`
